import './globals.css'
import { Inter } from 'next/font/google'
import ErrorBoundary from '@/components/errorBoundary'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorBoundary>
          {children}
        </ErrorBoundary>
      </body>
    </html>
  )
}

if (typeof window !== 'undefined') {
  window.addEventListener('error', (event) => {
    fetch('/api/report-error', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: event.message,
        stack: event.error?.stack || 'No stack trace',
        url: window.location.href,
      }),
    }).catch(console.error);
  });

  window.addEventListener('unhandledrejection', (event) => {
    fetch('/api/report-error', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: event.reason?.message || 'Unhandled Promise Rejection',
        stack: event.reason?.stack || 'No stack trace',
        url: window.location.href,
      }),
    }).catch(console.error);
  });
}