export const carBrands = [
    { value: "bmw", label: "BMW" },
    { value: "mercedes", label: "Mercedes" },
    { value: "audi", label: "Audi" },
    { value: "toyota", label: "Toyota" },
    { value: "volkswagen", label: "Volkswagen" },
    { value: "ford", label: "Ford" },
    { value: "opel", label: "Opel" },
    { value: "renault", label: "Renault" },
    { value: "peugeot", label: "Peugeot" },
    { value: "citroen", label: "Citroen" },
    { value: "volvo", label: "Volvo" },
    { value: "saab", label: "Saab" },
    { value: "skoda", label: "Skoda" },
    { value: "seat", label: "Seat" },
    { value: "hyundai", label: "Hyundai" },
    { value: "kia", label: "Kia" },
    { value: "nissan", label: "Nissan" },
    { value: "mazda", label: "Mazda" },
    { value: "subaru", label: "Subaru" },
    { value: "suzuki", label: "Suzuki" },
    { value: "honda", label: "Honda" },
    { value: "lexus", label: "Lexus" },
];