export const carModels = {
    bmw: ["3 Series", "5 Series", "X5", "i3"],
    mercedes: ["C-Class", "E-Class", "S-Class", "GLE"],
    audi: ["A4", "A6", "Q5", "e-tron"],
    toyota: ["Corolla", "Camry", "RAV4", "Prius"],
    volkswagen: ["Golf", "Passat", "Tiguan", "Polo"],
    ford: ["Focus", "Mustang", "Explorer", "F-150"],
    opel: ["Corsa", "Astra", "Insignia", "Zafira"],
    renault: ["Clio", "Megane", "Captur", "Kadjar"],
    peugeot: ["208", "308", "508", "e-208"],
    citroen: ["C3", "C4", "C5", "C-Elysee"],
    volvo: ["V40", "V60", "V70", "XC60"],
    saab: ["9-3", "9-5", "9-7", "9-3X"],
    skoda: ["Octavia", "Superb", "Kodiaq", "Fabia"],
    seat: ["Leon", "Ibiza", "Ateca", "Arona"],
    hyundai: ["i30", "i20", "Tucson", "Santa Fe"],
    kia: ["Ceed", "Sportage", "Niro", "Picanto"],
    nissan: ["Qashqai", "Altima", "Juke", "Leaf"],
    mazda: ["3", "6", "CX-5", "MX-5"],
    subaru: ["Impreza", "Legacy", "Outback", "Forester"],
    suzuki: ["Swift", "Vitara", "SX4", "Baleno"],
    honda: ["Civic", "Accord", "CR-V", "HR-V"],
    lexus: ["ES", "RX", "NX", "UX"],
};